### ISSUE TITLE
Where are my starred packages? the npmjs.com is brand new.

### ISSUE THREAD

**Issue by lgh06** [npm/www#376] opened 2018-04-14 15:02 UTC
I starred tens of packages...
Now where can I find them...?
and, for the new site, seems no star function?
thx.

**Comment by jefflembeck** [comment] 2018-04-15 16:55
So, for now, your best way to see what you've starred is through the CLI:

```
npm stars
```

We're working on making a new version of the service/interface for the website. Thanks for your patience:

dupe of https://github.com/npm/www/issues/375

**Closed as completed by jefflembeck** 2018-04-15 16:55 UTC
