### ISSUE TITLE
shows no README.md despite repo having one

### ISSUE THREAD

**Issue by noformnocontent** [npm/www#117] opened 2017-01-25 10:17 UTC
might be a single case 
- https://www.npmjs.com/package/ftp
- https://github.com/mscdex/node-ftp

plus i clearly remember reading it on npm site like a month ago

**Comment by Download** [comment] 2017-01-26 10:39
https://www.npmjs.com/package/events

I worked with npmjs.com and saw no issues, but today I see it everywhere.

**Comment by noformnocontent** [comment] 2017-01-26 10:47
i thought it might have something to do with readme size being over 32 kb, but https://github.com/Gozala/events/blob/master/Readme.md is _371 bytes_

**Comment by Reinmar** [comment] 2017-01-26 10:49
The same problem with https://www.npmjs.com/package/mgit2 and https://www.npmjs.com/package/@ckeditor/ckeditor5-dev-docs. It worked couple of days ago and we didn't change much in the readmes since then.

**Comment by nightskylark** [comment] 2017-01-26 12:12
The same problem with these packages:
https://www.npmjs.com/package/devextreme-angular
https://github.com/DevExpress/devextreme-angular

https://www.npmjs.com/package/devextreme-aspnet-data
https://github.com/DevExpress/DevExtreme.AspNet.Data

https://www.npmjs.com/package/devextreme-intl
https://github.com/DevExpress/DevExtreme-Intl

**Comment by EddSuarez** [comment] 2017-01-26 12:43
Same problem here:
https://www.npmjs.com/package/bix-notifications
https://github.com/EddSuarez/notifications

**Comment by Comandeer** [comment] 2017-01-26 12:46
Same for all my packages:
https://www.npmjs.com/~comandeer

**Comment by Download** [comment] 2017-01-27 14:17
Fixed now for the packages I mentioned... Hopefully for all?

**Comment by eahefnawy** [comment] 2017-01-30 16:29
We're facing the same issue at [Serverless](https://github.com/serverless/serverless)! 😞 

https://www.npmjs.com/package/serverless

**Comment by bcoe** [comment] 2017-01-30 18:40
@eahefnawy looking at the serverless package, there is no README file in the contents:

<img width="1026" alt="screen shot 2017-01-30 at 10 39 05 am" src="https://cloud.githubusercontent.com/assets/194609/22436327/6b0b0546-e6d8-11e6-86fb-c8d43c745060.png">

There was a bug in older versions of npm (I see you published with 3.9.5) that caused README.md to sometimes not be included in the tarball generated. Try upgrading your npm version, and publishing a patch release of the module -- sorry for the inconvenience.

**Closed** 2017-01-30 19:03 UTC

**Comment by eahefnawy** [comment] 2017-01-31 10:22
Thanks @bcoe ... I just published a patch and the issue is now resolved 😊
