### ISSUE TITLE
Problems with statistic due to letter case

### ISSUE THREAD

**Issue by 1001v** [npm/www#68] opened 2016-11-20 11:14 UTC
Hello. I've published a package named [Range.js](https://www.npmjs.com/package/Range.js), but i've got statistic for it from another package named [range.js](https://www.npmjs.com/package/range.js). I mean, this two packages now have common statistic. It seems like problem somethere in sql syntax, but that's just a supposition. Thank you.

**Comment by 1001v** [comment] 2016-11-20 11:16
I believe (that)[https://github.com/npm/www/issues/65] is the same issue, didn't noticed it, sorry. Probably, we should close this one then.

**Comment by aredridel** [comment] 2016-11-20 14:38
Duplicate of https://github.com/npm/registry/issues/38

**Closed by aredridel** 2016-11-20 14:38 UTC
