### ISSUE TITLE
Shows 0 downloads for last day

### ISSUE THREAD

**Issue by deQuota** [npm/www#293] opened 2018-01-27 05:47 UTC
## Link to the page
https://www.npmjs.com/
## Logged in or logged out?
logged in
## Actual behavior
Downloads · Last Day
0
## Browser with version
Chrome
## Any error message?

**Comment by awaitlink** [comment] 2018-01-27 16:35
Duplicate of #280.

**Closed as completed** 2018-01-28 10:22 UTC
