### ISSUE TITLE
The Promise and promise package have same statistics

### ISSUE THREAD

**Issue by imyzf** [npm/www#65] opened 2016-11-17 02:33 UTC
`Promise` and `promise` are different packages, but they have same statistics. Dose the npm website regard them as the same package and make same statistics?

link:  
https://www.npmjs.com/package/Promise  
https://www.npmjs.com/package/promise

![image](https://cloud.githubusercontent.com/assets/8298849/20374097/267753a0-acb1-11e6-9503-709d4d191ed4.png)

**Comment by 1001v** [comment] 2016-11-20 11:18
I can confirm this problem with [range.js](https://www.npmjs.com/package/range.js) and [Range.js](https://www.npmjs.com/package/Range.js) packages.

**Comment by aredridel** [comment] 2016-11-20 14:38
Duplicate of https://github.com/npm/registry/issues/38

**Closed by aredridel** 2016-11-20 14:38 UTC
