### ISSUE TITLE
npm React page not loading correctly 

### ISSUE THREAD

**Issue by charliebarber** [npm/www#394] opened 2018-05-01 20:37 UTC
Just displays this 

![screen shot 2018-05-01 at 21 36 38](https://user-images.githubusercontent.com/37746832/39492512-c16af100-4d87-11e8-8ca8-b37ae8acfbd4.png)

**Comment by jefflembeck** [comment] 2018-05-02 18:26
Closing as a dupe of #393

**Closed as completed by jefflembeck** 2018-05-02 18:26 UTC
