### ISSUE TITLE
npm library single pages don't support h4-h6 tags in markdown

### ISSUE THREAD

**Issue by revelt** [npm/www#105] opened 2017-01-11 14:13 UTC
Hi all,

It looks like npm single pages don't recognise the `h4`, `h5` and `h6` markdown notation in hashes. Some [libraries](https://www.npmjs.com/package/json-normalizer) describe all their API's using `h` tags and while it works on GitHub, npm shows only bunch of hashes.

![screen shot 2017-01-11 at 14 12 03](https://cloud.githubusercontent.com/assets/8344688/21851654/f2a04adc-d807-11e6-8725-1bf5189875ff.png)

**Comment by aredridel** [comment] 2017-01-12 15:09
Duplicate of #103, which is on the component `marky-markdown` as https://github.com/npm/marky-markdown/issues/324

**Closed by aredridel** 2017-01-12 15:09 UTC

**Comment by revelt** [comment] 2017-01-12 15:13
Oh

**Comment by aredridel** [comment] 2017-01-12 15:14
No worries! Just keeping our tracker tidy so we can keep an eye on issues clearly.
